---
title: "NeoImmuno.lineage_identification"
author: "Yuanxin Xi and Jing Wang"
date: "6/2/2022"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: "hide"
---


## load data
```{r}
library(Seurat)
library(ComplexHeatmap)
library(readxl)
library(ggplot2)
library(png)
library(grid)
setwd("/projects2/yxi/Tina_Cascone/")
ll = load("report/SC307.RData/neoimmuno.final_no_prolif.RData")
data = as.matrix(sc@assays$RNA@data)
sdata = as.matrix(sc@assays$integrated@scale.data)
load("report/SC307.RData/neoimmuno.cell_annotation.RData")
cid = sapply(cell_ann2[colnames(sc)], function(x) strsplit(x, ".", fixed=T)[[1]][1])
cids = unique(cid)
cell_col = c("Lymphoid"="hotpink", "Myeloid"="green2", "Stromal"="deepskyblue", "Epithelial"="orange", "Proliferating"="grey")
cid1 = sapply(gsub("Stromal.", "", cell_ann[colnames(sc)], fixed=T), function(x) strsplit(x, ".", fixed=T)[[1]][1])
cids1 = unique(cid1)

pdf(sprintf("report/SC307.report_12.neoimmuno.figure/Major_lineage.umap_plot.pdf"), width=8, height=8)
plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap)), las=1, col=cell_col[cid], xlim=c(min(umap[,1]), max(umap[, 1])))
pos = 2
for(c in cids1){
  dd = colMeans(umap[cid1==c, ])
  text(dd[1], dd[2], labels=c, cex=1.2, pos=pos + 1, offset=0)
  pos = (pos + 2) %% 4
}
dev.off()

cid2 = sapply(cell_cluster[colnames(sc)], function(x) paste(strsplit(x, ".", fixed=T)[[1]][2:4], collapse="."))
cid2 = gsub("Lymphoid", "L", cid2, fixed=T)
cid2 = gsub("cluster", "C", cid2, fixed=T)
cid2 = gsub("Proliferating", "P", cid2, fixed=T)
cid2 = gsub("Innate", "I", cid2, fixed=T)
cid2 = gsub("cluster", "C", cid2, fixed=T)
cid2 = gsub("+ T", "", cid2, fixed=T)
cid2 = gsub("_v[0-9]", "", cid2)
cid2 = gsub(".NA", "", cid2, fixed=T)
cid2s = unique(cid2) 
cid2_col = sample(rainbow(length(cid2s)))
names(cid2_col) = cid2s

pdf(sprintf("report/SC307.report_12.neoimmuno.figure/Major_lineage.umap_plot1.pdf"), width=8, height=8)
plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap)), las=1, col=cid2_col[cid2], xlim=c(min(umap[,1]), max(umap[, 1])))
pos = 2
for(c in cid2s){
  dd = colMeans(umap[cid2==c, ])
  text(dd[1], dd[2], labels=c, cex=0.8)
  pos = (pos + 2) %% 4
}
dev.off()
```


## SingleR Annotation 
```{r}
library(ggplot2)
library(png)
library(grid)

library(SingleR)
scc = as.SingleCellExperiment(sc)
library(celldex)
hpca.se <- HumanPrimaryCellAtlasData()
sr1 = SingleR(test=scc, ref=hpca.se, assay.type.test=1, labels = hpca.se$label.main)
ref.se <- DatabaseImmuneCellExpressionData()
sr2 = SingleR(test=scc, ref=ref.se, assay.type.test=1, labels = ref.se$label.main)
sc = AddMetaData(sc, metadata=sr1$pruned.labels, col.name="label1"); gc()
sc = AddMetaData(sc, metadata=sr2$pruned.labels, col.name="label2"); gc()

label = sc@meta.data$label2
label[is.na(label)] = "NA"
lbl = table(label)
misc = names(lbl)[lbl<100]
label[label %in% misc] = "Misc"
labels = unique(label)
label_col = rainbow(length(labels))
names(label_col) = labels
pdf("report/SC307.report_12.neoimmuno.figure/singleR/annotation2.pdf", width=9, height=8)
plot(umap[,1], umap[,2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Pooled samples(n = %d)", nrow(umap)), las=1, col=label_col[label])
legend("topright", legend=labels, pch=16, col=label_col, cex=0.8)

for(ll in labels){
  show(ll)
  plot(umap[,1], umap[,2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("%s (n = %d)", ll, table(label)[ll]), las=1, col="grey")
  points(umap[label==ll, 1], umap[label==ll, 2], col="blue", cex=0.5, pch=20)
}
dev.off()

feature_plot_png2 = function(gname, gdata, folder=".") {
  gtmp = sprintf("%s/%s.tmp", folder, gname)
  dir.create(gtmp, showWarnings=F)
  ifiles = list()
  for(i in 1:ncol(gdata)) {
    img_file = sprintf("%s/%s.feature_plot.png", gtmp, i)
    gg = colnames(gdata)[i]
    show(c(gname, gg))
    png(file=img_file, width=560, height=490) #, quality=100)
    dd = data.frame(UMAP1=umap[,1], UMAP2=umap[,2], SR_score=gdata[, i])
    dd$SR_score = fix_percentile(dd$SR_score, 0.001)
    dd = dd[order(dd$SR_score), ]
    ggp = ggplot(dd, aes(x=UMAP1, y=UMAP2, colour=SR_score)) + geom_point(size=0.5) + scale_colour_gradientn(colors=c("lightgray", "yellow", "red")) + ggtitle(sprintf("%s: %s", gname, gg))
    show(ggp)
    dev.off()
    ifiles[[gg]] = readPNG(img_file, native=T)
  }
  
  pdf(file=sprintf("%s/%s.singleR_score.pdf", folder, gname), width=8, height=7)
  grid.raster(ifiles[[1]])
  lapply(ifiles[-1], function(x) {grid.newpage(); grid.raster(x)}) -> bquiet
  dev.off()
  unlink(gtmp, recursive=T)
}

feature_plot_png2("Human_Prime_Cell", sr1$scores, folder="report/SC307.report_12.neoimmuno.figure/singleR") 
feature_plot_png2("Immune_Cell", sr2$scores, folder="report/SC307.report_12.neoimmuno.figure/singleR") 

```

## project to previous cluster
```{r}
cell_cluster1 = gsub(".C", ".", gsub("cluster", "C", gsub("neoimmuno.", "", cell_cluster[colnames(sc)], fixed=T), fixed=T), fixed=T)
cid2 = sapply(cell_cluster1, function(x) strsplit(x, ".", fixed=T)[[1]][1])
cids2 = unique(cid2)
cid2_col = rainbow(length(cids2))
names(cid2_col) = cids2

pdf(sprintf("report/SC307.report_12.neoimmuno.figure/Cluster_projection.umap_plot.pdf"), width=8, height=8)
plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap)), las=1, col=cid2_col[cid2])
for(c in cids2){
  dd = colMeans(umap[cid2==c, ])
  text(dd[1], dd[2], labels=c, cex=1.2)
}
for(c in cids2){
  cells1 = names(cell_cluster1)[cid2==c]
  umap1 = umap[cells1, ]
  cell_subcluster = cell_cluster1[cells1]
  if(length(unique(cell_subcluster))==1) next
  cell_subcluster = sapply(cell_subcluster, function(x) paste(strsplit(x, ".", fixed=T)[[1]][1:2], collapse="."))
  show(table(cell_subcluster))
  sub_col = rainbow(length(unique(cell_subcluster)))
  names(sub_col) = unique(cell_subcluster)
  plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("%s (n = %d)", c, length(cells1)), las=1, col="gray")
  points(umap1[, 1], umap1[, 2], pch=20, col=sub_col[cell_subcluster], cex=0.3)
  for(c1 in unique(cell_subcluster)){
    dd = colMeans(umap1[cell_subcluster==c1, ])
    text(dd[1], dd[2], labels=c1, cex=1.2)
  }
}
dev.off()
```

## bubble plot
```{r}
bubble_plot = function(gname, glist, grouping, folder=".", groups=c(), size=c(7, 7), lim=2) {
if(length(groups)==0) {
  groups = names(glist)
  names(groups) = groups
}
df = data.frame()
ordered_gene = c()
for(gn in names(groups)){
  show(gn)
  for(gg in glist[[gn]]){
    dd = data[1, ] * 0; sdd = sdata[1, ] * 0
    if(gg %in% rownames(data)) dd = data[gg, ]
    if(gg %in% rownames(sdata)) sdd = c(scale(sdata[gg, ]))
    for(pp in names(groups)){
      if(pp=="NA") next
#      show(c(gn, gg, pp))
      d1 = dd[grouping==groups[pp]]; sd1 = sdd[grouping==groups[pp]]
      pctg = sum(d1>0) / length(d1) * 100
      avg = 0
#      if(sum(d1>0)>0) avg = mean(d1) / max(dd)
      if(sum(d1>0)>0) avg = mean(sd1)
      df = rbind(df, data.frame(Group=pp, Gene=gg, Pctg=pctg, Exp=avg))
    }
  }
  if(gn=="NA") {
    ordered_gene = c(glist[[gn]], ordered_gene)
  } else {
    ordered_gene = c(glist[[gn]][order(df$Pctg[df$Group==gn & df$Gene %in% glist[[gn]]])], ordered_gene)
  }
}
df$Gene = factor(df$Gene, levels=ordered_gene)
df$Group = factor(df$Group, levels=names(groups))
emax = lim; emin = -lim
df$Exp[df$Exp>emax] = emax
df$Exp[df$Exp<emin] = emin
pdf(file=sprintf("%s%s.bubble_plot.pdf", folder, gname), width=size[1], height=size[2])
ggp = ggplot(df, aes(x=Group, y=Gene, size=Pctg)) + geom_point(aes(fill=Exp), pch=21, color="black") + scale_fill_gradient(low="darkblue", high="yellow", name="Mean Exp", limits=c(emin, emax)) + scale_size_area(breaks=c(0,20,40,60,80,100), labels=c("0%", "20%", "40%", "60%", "80%", "100%"), name="% Cells") + theme(panel.grid.major=element_line(colour="lightgrey", linetype="dotted", size=0.5), panel.background = element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), axis.text.x=element_text(angle=45, hjust=0, size=14, face="bold"), axis.text.y=element_text(size=14, face="italic"), legend.text=element_text(size=14), legend.title=element_text(size=14, face="bold")) + scale_x_discrete(position="top") 

show(ggp)
dev.off()
return(df)
}

```


## bubble plot landscape
```{r}
bubble_plot_landscape = function(gname, glist, grouping, folder=".", groups=c(), size=c(7, 7), lim=2) {
if(length(groups)==0) {
  groups = names(glist)
  names(groups) = groups
}
df = data.frame()
ordered_gene = c()
for(gn in names(groups)){
  show(gn)
  for(gg in glist[[gn]]){
    dd = data[1, ] * 0; sdd = sdata[1, ] * 0
    if(gg %in% rownames(data)) dd = data[gg, ]
    if(gg %in% rownames(sdata)) sdd = c(scale(sdata[gg, ]))
    for(pp in names(groups)){
      if(pp=="NA") next
#      show(c(gn, gg, pp))
      d1 = dd[grouping==groups[pp]]; sd1 = sdd[grouping==groups[pp]]
      pctg = sum(d1>0) / length(d1) * 100
      avg = 0
#      if(sum(d1>0)>0) avg = mean(d1) / max(dd)
      if(sum(d1>0)>0) avg = mean(sd1)
      df = rbind(df, data.frame(Group=pp, Gene=gg, Pctg=pctg, Exp=avg))
    }
  }
  if(gn=="NA") {
    ordered_gene = c(ordered_gene, glist[[gn]])
  } else {
    ordered_gene = c(ordered_gene, glist[[gn]][order(df$Pctg[df$Group==gn & df$Gene %in% glist[[gn]]], decreasing=T)])
  }
}
df$Gene = factor(df$Gene, levels=ordered_gene)
df$Group = factor(df$Group, levels=rev(names(groups)))
emax = lim; emin = -lim
df$Exp[df$Exp>emax] = emax
df$Exp[df$Exp<emin] = emin
pdf(file=sprintf("%s%s.bubble_plot.pdf", folder, gname), width=size[1], height=size[2])
ggp = ggplot(df, aes(y=Group, x=Gene, size=Pctg, color=Exp)) + geom_point() + scale_color_gradient(low="darkblue", high="yellow", name="Mean Exp", limits=c(emin, emax)) + scale_size_area(breaks=c(0,20,40,60,80,100), labels=c("0%", "20%", "40%", "60%", "80%", "100%"), name="% Cells") + theme(panel.grid.major=element_line(colour="lightgrey", linetype="dotted", size=0.5), panel.background = element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), axis.text.x=element_text(angle=45, hjust=0, size=9, face="italic"), axis.text.y=element_text(size=14, face="bold"), legend.text=element_text(size=14), legend.title=element_text(size=14, face="bold")) + scale_x_discrete(position="top") + theme(legend.box = "horizontal") 

show(ggp)
dev.off()
return(df)
}

markers = list("Lymphoid"=c("PTPRC", "CD3E", "CD40LG", "CD8A", "CD8B", "CD19", "CD79A", "MS4A1", "GZMA", "GZMB", "NCAM1", "KLRB1", "KLRC1"), "Myeloid"=c("CD14", "CD68", "CD1C", "S100A8", "S100A9", "MS4A2", "ITGAX", "LILRB4", "LILRA4"), "Stromal"=c("CLDN5", "COL1A2", "COL1A1", "ACTA2", "PDGFRB", "ACKR1"), "Epithelial"=c("EPCAM", "NKX2-1", "KRT17", "KRT8", "MUC5B"))

df = bubble_plot_landscape("Major_lineage", markers, cid, folder=sprintf("report/SC307.report_12.neoimmuno.figure/"), groups=c("Lymphoid"="Lymphoid", "Myeloid"="Myeloid", "Stromal"="Stromal", "Epithelial"="Epithelial"), size=c(10, 2.5), lim=1)
```

## Sub Lineages
```{r}
library(Seurat)
library(ComplexHeatmap)
library(readxl)
library(ggplot2)
setwd("/projects2/yxi/Tina_Cascone/")
ll = load("report/SC307.RData/neoimmuno.final_no_prolif.RData")
cid0 = sapply(cell_ann2[colnames(sc)], function(x) strsplit(x, ".", fixed=T)[[1]][2])
umap0 = umap
cc = "Epithelial"
ll = load(sprintf("report/SC307.RData/neoimmuno.%s.RData", cc)); gc()
data = as.matrix(sc@assays$RNA@data)
sdata = as.matrix(sc@assays$integrated@scale.data)
load("report/SC307.RData/neoimmuno.cell_annotation.RData")
umap = sc@reductions$umap@cell.embeddings
cid = sapply(cell_ann2[colnames(sc)], function(x) strsplit(x, ".", fixed=T)[[1]][2])
cid1 = cid0
if(cc=="Myeloid") {
  cid = gsub(" ", "\n", cid)
  cid1 = gsub(" ", "\n", cid1)
}
if(cc=="Proliferating") cid = gsub(" Lymphoid", "\nLymphoid", cid)
cids = unique(cid)
cell_col = rainbow(length(cids))
names(cell_col) = cids

pdf(sprintf("report/SC307.report_12.neoimmuno.figure/%s.umap_plot.pdf", cc), width=8, height=8)
plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap)), las=1, col=cell_col[cid], xlim=c(min(umap[,1]), max(umap[, 1])))
pos = 0
for(c in cids){
  dd = colMeans(umap[cid==c, ])
  text(dd[1], dd[2], labels=c, cex=1.2, pos=pos+1)
  pos = (pos + 2) %% 4
}
plot(umap0[, 1], umap0[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap)), las=1, col="gray", xlim=c(min(umap0[,1]), max(umap0[, 1])))
pos = 0
for(c in cids){
  points(umap0[cid1==c, 1], umap0[cid1==c, 2], pch=20, cex=0.3, col=cell_col[c])
  dd = colMeans(umap0[cid1==c, ])
  text(dd[1], dd[2], labels=c, cex=1.2, pos=pos+1)
  pos = (pos + 2) %% 4
}

dev.off()

markers = list(
  "Myeloid"=list("Classical monocytes"=c("S100A8", "S100A9", "CSF3R", "FCN1"), "Neutrophils"=c("IL1A", "IL1B", "IL6", "CXCL8"), "Non-classical monocytes"=c("FCGR3A", "LILRB2", "CDKN1C", "CD14"), "M2-like macrophages"=c("CD163", "MSR1", "SELENOP", "C1QA"), "Alveolar macrophages"=c("MARCO", "MCEMP1", "PPARG"), "CXCL9+ TAMs"=c("CXCL9"), "cDC2"=c("CD1C", "CLEC4A", "CLEC10A", "FCER1A"), "cDC1"=c("CLEC9A", "CLNK", "XCR1", "CADM1", "BATF3", "CD226"), "pDC"=c("UGCG", "CLEC4C", "LILRA4", "IRF4", "ITM2C"), "Mast cells"=c("MS4A2", "TPSAB1", "CPA3")),
  "Lymphoid"=list("CD4+ T cells"=c("CD3D", "CD3G", "CD4", "IL7R", "LEF1", "CD40LG", "FOXP3", "IL2RA"), "CD8+ T cells"=c("CD8A", "CD8B", "GZMB", "GZMH"), "Innate Lymphoid"=c("NKG7", "GNLY", "PRF1", "NCAM1", "FCGR3A", "NCR1", "TYROBP", "TRDC", "RORC"), "B cells"=c("CD79A", "CD79B", "CD19", "MS4A1", "CD22"), "Plasma"=c("JCHAIN", "MZB1", "SDC1", "SLAMF7")),
  "Proliferating"=list("T cells"=c("CD3D", "CD3G", "CD8A", "CD8B", "LAG3", "CTLA4"), "Innate lymphoid"=c("FCGR3A", "NCAM1", "NCR1", "NCR3", "NKG7", "TRGC1", "TRDC"), "B/plasmablast"=c("CD19", "MS4A1", "CD79A", "CD27", "BCL6", "CD24", "CD80", "IGHM", "IGHG1", "BACH2", "CD79B", "BIK", "JCHAIN", "IGKC", "IGHA1", "MZB1", "TNFRSF17", "CD38", "S1PR2"), "Myeloid"=c("CST3", "LYZ", "CSF1R", "CD68", "CD1C", "IL18"), "Other"=c(), "NA"=c("TUBB", "BIRC5", "TYMS"))
)

groups = list(
  "Myeloid"=c("Classical monocytes"="Classical\nMonocytes", "Neutrophils"="Neutrophils", "Non-classical monocytes"="Non-classical\nmonocytes", "M2-like macrophages"="M2-like\nmacrophages", "Alveolar macrophages"="Alveolar\nmacrophages", "CXCL9+ TAMs"="TAMs", "cDC2"="cDC2", "cDC1"="cDC1", "pDC"="pDC", "Mast cells"="Mast"), 
  "Lymphoid"=c("CD4+ T cells"="CD4+ T", "CD8+ T cells"="CD8+ T", "Innate Lymphoid"="Innate", "B cells"="B", "Plasma"="Plasma"),
  "Proliferating"=c("T cells"="T cell", "Innate lymphoid"="Innate\nLymphoid", "B/plasmablast"="B cell", "Myeloid"="Myeloid", "Other"="Other", "NA"="Pan Prolif")
)

sizes = list("Myeloid"=c(6, 10), "Lymphoid"=c(4, 8.5), "Proliferating"=c(4, 10))
sizes = list("Myeloid"=c(13, 4), "Lymphoid"=c(10, 2.5), "Proliferating"=c(12, 2.5))

df = bubble_plot_landscape(cc, markers[[cc]], cid, folder=sprintf("report/SC307.report_12.neoimmuno.figure/"), size=sizes[[cc]], groups=groups[[cc]], lim=1)
```


## Lymphoid Sub Lineages
```{r}
library(Seurat)
library(ComplexHeatmap)
library(readxl)
library(ggplot2)
setwd("/projects2/yxi/Tina_Cascone/")
ll = load("report/SC307.RData/neoimmuno.final_no_prolif.RData")
umap0 = umap
ll = load("report/SC307.RData/neoimmuno.Lymphoid.RData")
umap1 = umap
cc = "CD8+ T"
ll = load(sprintf("report/SC307.RData/neoimmuno.Lymphoid.%s.RData", cc))
data = as.matrix(sc@assays$RNA@data)
sdata = as.matrix(sc@assays$integrated@scale.data)
load("report/SC307.RData/neoimmuno.cell_annotation.RData")
cells = colnames(sc)
cid = sapply(cell_ann2[cells], function(x) strsplit(x, ".", fixed=T)[[1]][3])
cids = unique(cid)
cell_col = rainbow(length(cids))
names(cell_col) = cids
for(cn in names(cell_col)) show(cell_col[cn])

pdf(sprintf("report/SC307.report_12.neoimmuno.figure/Lymphoid.%s.umap_plot.pdf", cc), width=8, height=8)
plot(umap[, 1], umap[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("%s (n = %d)", cc, nrow(umap)), las=1, col=cell_col[cid])
pos = 0
for(c in cids){
  dd = colMeans(umap[cid==c, ])
  c1 = sprintf('"%s"', gsub('low', '"^"low"~"', gsub("high", '"^"high"~"', c)))
  text(dd[1], dd[2], labels=parse(text=c1), cex=1, pos=pos+1)
  pos = (pos + 2) %% 4
}
plot(umap1[, 1], umap1[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Lymphoid cells (n = %d)", nrow(umap1)), las=1, col="gray")
uu = umap1[cells, ]
points(uu[, 1], uu[, 2], pch=20, cex=0.3, col=cell_col[cid])
for(c in cids){
  dd = colMeans(uu[cid==c, ])
  c1 = sprintf('"%s"', gsub('low', '"^"low"~"', gsub("high", '"^"high"~"', c)))
  text(dd[1], dd[2], labels=parse(text=c1), cex=1)
}
plot(umap0[, 1], umap0[, 2], pch=20, xlab="UMAP1", ylab="UMAP2", cex.axis=1.5, cex.lab=1.5, cex.main=1.5, cex=0.3, font.axis=1.5, font.lab=1.5, main=sprintf("Total cells (n = %d)", nrow(umap0)), las=1, col="gray")
uu = umap0[cells, ]
points(uu[, 1], uu[, 2], pch=20, cex=0.3, col=cell_col[cid])
for(c in cids){
  dd = colMeans(uu[cid==c, ])
  c1 = sprintf('"%s"', gsub('low', '"^"low"~"', gsub("high", '"^"high"~"', c)))
  text(dd[1], dd[2], labels=parse(text=c1), cex=1)
}
dev.off()
```

## Lymphoid sublineage bubble plot
```{r}
markers = list(
  "CD8+ T" = list("Memory"=c("IL7R"), "KLRC1+ Trm"=c("KLRC1", "ZNF683", "HOPX", "ITGA1", "ITGAE"), "GZMK high Tem"=c("GZMK", "EOMES", "CMC1"), "Term eff/Tem"=c("KLRD1", "TBX21", "FCGR3A", "CX3CR1", "GZMH", "GNLY", "NKG7", "ASCL2", "TYROBP"), "Effector"=c(), "Exhausted"=c("TIGIT", "LAG3", "CTLA4", "ENTPD1", "GZMB", "COTL1", "CXCL13", "PDCD1"), "CXCL13 high"=c(), "HSPA1A/B high"=c("HSPA1A", "HSPA1B", "FOS"), "Stressed"=c("MT1X", "MT1E", "CREM")),
  "Innate" = list("CD56+/CD16+ NK"=c("NCAM1", "FCGR3A", "TYROBP", "IL2RB", "PRF1", "KIR3DL1", "KIR2DL1", "KIR2DL3", "GZMB", "KLRD1", "KLRK1", "KLRF1"), "CD56+/CD16- NK c1"=c("XCL1", "XCL2", "KLRC1", "GZMK"), "CD56+/CD16- NK c2"=c(), "Gamma delta T"=c("CD3D", "CD3G", "TRDV2", "TRGC2", "GZMH", "KLRG1"), "KIT high ILC"=c("IL7R", "KIT", "LTB", "RORC", "IL1R1", "IL23R", "CCR6", "AHR")),
  "CD4+ T" = list("Naïve"=c("LEF1", "SELL", "CCR7", "MAL"), "Memory"=c("IL7R", "CD40LG"), "GZMK+ Memory"=c("GZMK", "GZMA"), "Other CD4+"=c("CD69"), "Treg"=c("TNFRSF4", "FOXP3", "IL2RA", "IKZF2", "CTLA4", "TNFRSF1B", "TNFRSF18", "TIGIT", "CD27"), "TIGIT+ CD27+"=c(), "Tfh"=c("CXCL13", "PDCD1", "TOX", "TOX2"), "Stress response"=c("HSPA1A", "HSPA1B", "DNAJB1", "DUSP1", "JUN", "BAG3"), "Stressed"=c("MT2A", "MT1X", "MT1E"))
)

groups = list(
  "CD8+ T" = c("Memory"="Memory", "KLRC1+ Trm"="KLRC1+ Trm", "GZMK high Tem"="GZMK high Tem", "Term eff/Tem"="Term effector", "Effector"="Effector", "Exhausted"="Exhausted", "CXCL13 high"="CXCL13 high", "HSPA1A/B high"="HSPA1A/B high", "Stressed"="Stressed", "NA"="NA"),
  "Innate"= c("CD56+/CD16+ NK"="CD56+/CD16+ NK", "CD56+/CD16- NK c1"="CD56+/CD16- NK c1", "CD56+/CD16- NK c2"="CD56+/CD16- NK c2", "Gamma delta T"="Gamma delta T", "KIT high ILC"="KIT high ILC"),
  "CD4+ T" = c("Naïve"="LEF1 high Naïve", "Memory"="Memory", "GZMK+ Memory"="GZMK+ Memory", "Other CD4+"="Other", "Treg"="Treg", "Tfh"="Tfh", "TIGIT+ CD27+"="TIGIT+ CD27+", "Stress response"="Stress response", "Stressed"="Stressed")

)

sizes = list("CD8+ T"=c(10, 3.5), "Innate"=c(11, 2.5), "CD4+ T"=c(11, 3.5))

df = bubble_plot_landscape(cc, markers[[cc]], cid, folder=sprintf("report/SC307.report_12.neoimmuno.figure/Lymphoid."), size=sizes[[cc]], groups=groups[[cc]], lim=1)

```


# Appendix
```{r}
sessionInfo()
```
